//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TimeclockEntities : DbContext
    {
        public TimeclockEntities()
            : base("name=TimeclockEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<job_numbers> job_numbers { get; set; }
        public virtual DbSet<work_types> work_types { get; set; }
        public virtual DbSet<entry> entries { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
