//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_numbers
    {
        public job_numbers()
        {
            this.entries = new HashSet<entry>();
        }
    
        public string job_number { get; set; }
        public System.Guid id { get; set; }
        public System.Guid user_id { get; set; }
    
        public virtual ICollection<entry> entries { get; set; }
        public virtual user user { get; set; }
    }
}
