//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.entries = new HashSet<entry>();
            this.work_types = new HashSet<work_types>();
            this.job_numbers = new HashSet<job_numbers>();
        }
    
        public string email { get; set; }
        public string name { get; set; }
        public System.Guid department_id { get; set; }
        public string password { get; set; }
        public System.Guid token { get; set; }
        public System.Guid id { get; set; }
    
        public virtual ICollection<entry> entries { get; set; }
        public virtual ICollection<work_types> work_types { get; set; }
        public virtual ICollection<job_numbers> job_numbers { get; set; }
    }
}
